#!/usr/bin/env python3
"""biject_to compatibility spike.

For every distribution registered in `effectful.handlers.numpyro`,
construct a minimal valid instance via `_dist_introspection` and call
`numpyro.distributions.transforms.biject_to(d.support)`. Tabulate the
result so the compile pass knows which distributions need special
casing.

Output: prints a Markdown table to stdout and writes the same to
`docs/biject_to_compatibility.md`.

Acceptance threshold: every failure must have either (a) a workaround
inside `_DistributionTerm` or (b) an explicit deferred-distribution
note. The script exits non-zero if any of the load-bearing
distributions {Normal, HalfNormal, Beta, Dirichlet, LKJCholesky,
Independent} fail outright (distinguished from "no real-line
bijection," which is expected for discrete distributions and is
recorded as a skip rather than a fail).
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

import numpyro.distributions as dist
from numpyro.distributions.transforms import biject_to

from effectful_mcmc._dist_introspection import (
    DISCRETE_CONSTRAINT_NAMES,
    list_registered_distributions,
    default_factory,
)

# Distributions that the bridge guarantees work at "ok" or "known-issue"
# level. `TransformedDistribution` is *not* listed here because effectful
# doesn't ship a wrapper for it (so it never enters the registered set
# the spike iterates over).
LOAD_BEARING = {
    "Normal", "HalfNormal", "Beta", "Dirichlet", "LKJCholesky", "Independent",
}


@dataclass
class Row:
    name: str
    status: str             # "ok" | "skip-discrete" | "no-factory" | "fail" | "known-issue"
    detail: str             # transform class on ok; constraint or error otherwise


# Distributions whose `support` returns an unevaluated Term instead of a
# concrete Constraint, due to effectful's `_DistributionTerm._is_eager`
# check returning False whenever any arg is itself a `Term` — even when
# the inner Term is fully eager. The bridge's compile pass needs to
# materialize these via a helper before calling `numpyro.sample`.
KNOWN_TERM_SUPPORT_BUG = {"Independent"}


def is_discrete(constraint) -> bool:
    """Is this constraint expected to have no real-line bijection?"""
    return type(constraint).__name__ in DISCRETE_CONSTRAINT_NAMES


def run_one(d_cls: type[dist.Distribution]) -> Row:
    name = d_cls.__name__
    try:
        d = default_factory(d_cls)()
    except KeyError:
        return Row(name, "no-factory", "no entry in _FACTORIES")
    except Exception as e:
        return Row(name, "fail", f"construction: {type(e).__name__}: {e}")

    try:
        support = d.support
    except Exception as e:
        return Row(name, "fail", f"d.support: {type(e).__name__}: {e}")

    # Check for the known _is_eager-too-conservative case: support comes
    # back as an unevaluated effectful Term instead of a Constraint.
    if type(support).__name__ == "_CallableTerm":
        return Row(name, "known-issue",
                   "d.support returned _CallableTerm (effectful _is_eager too "
                   "conservative when args contain Terms); the compile pass "
                   "materializes via dist.<cls>(*evaluated_args).support")

    try:
        transform = biject_to(support)
    except NotImplementedError:
        if is_discrete(support):
            return Row(name, "skip-discrete",
                       f"{type(support).__name__} has no real-line bijection")
        return Row(name, "fail",
                   f"biject_to({type(support).__name__}) not implemented")
    except Exception as e:
        return Row(name, "fail",
                   f"biject_to({type(support).__name__}): {type(e).__name__}: {e}")

    return Row(name, "ok", type(transform).__name__)


def format_markdown(rows: list[Row]) -> str:
    out = ["# biject_to compatibility",
           "",
           "Generated by `scripts/biject_to_spike.py`. Re-run with:",
           "",
           "```",
           "python scripts/biject_to_spike.py",
           "```",
           "",
           "## Results",
           "",
           "| Status | Distribution | Detail |",
           "|---|---|---|"]
    status_order = {"ok": 0, "skip-discrete": 1, "known-issue": 2,
                    "no-factory": 3, "fail": 4}
    for r in sorted(rows, key=lambda r: (status_order[r.status], r.name)):
        out.append(f"| {r.status} | `{r.name}` | {r.detail} |")
    out.append("")
    n_ok    = sum(1 for r in rows if r.status == "ok")
    n_skip  = sum(1 for r in rows if r.status == "skip-discrete")
    n_known = sum(1 for r in rows if r.status == "known-issue")
    n_nofac = sum(1 for r in rows if r.status == "no-factory")
    n_fail  = sum(1 for r in rows if r.status == "fail")
    out += ["",
            "## Summary",
            "",
            f"- {n_ok} ok",
            f"- {n_skip} skipped (discrete; no real-line bijection)",
            f"- {n_known} known issue (workaround in the bridge's compile pass)",
            f"- {n_nofac} no factory (introspection gap)",
            f"- {n_fail} failed",
            "",
            "## Known issues for the bridge to handle",
            "",
            "**`Independent`** — `effectful.handlers.numpyro.IndependentTerm`'s ",
            "`support` returns an unevaluated effectful `_CallableTerm` instead of ",
            "the concrete `IndependentConstraint`. The root cause is in ",
            "`effectful/effectful/handlers/numpyro.py` — `_DistributionTerm._is_eager` ",
            "returns `False` whenever any constructor arg is itself a `Term`, even ",
            "when the inner Term is fully concrete (e.g. `Normal(jnp.zeros(2), jnp.ones(2))` ",
            "is a `NormalTerm` with eager arg arrays but still a `Term`).",
            "",
            "Bare `numpyro.distributions.Independent(Normal(jnp.zeros(2), jnp.ones(2)), 1).support` ",
            "returns `IndependentConstraint(Real(), 1)` and `biject_to` returns ",
            "`IndependentTransform` correctly. The bridge's compile pass detects ",
            "`_DistributionTerm`s whose `support` is a `_CallableTerm` and recursively ",
            "materializes them via `dist.<cls>(*evaluated_args, **evaluated_kwargs)` ",
            "before computing the constraint. This avoids modifying effectful itself ",
            "for the initial bridge release.",
            "",
            "Upstream fix: generalize `_is_eager` to recurse into Term args rather ",
            "than treating any Term as non-eager.",
            ""]
    return "\n".join(out)


def main() -> int:
    """Write the compatibility table to docs/biject_to_compatibility.md.

    Output goes to the committed doc file; the script is the source of
    truth and the doc is the artefact. Re-run after every effectful
    bump and commit the regenerated doc. Exit non-zero if any
    load-bearing distribution fails without a known workaround.
    """
    classes = list_registered_distributions()
    rows = [run_one(c) for c in classes]
    md = format_markdown(rows)

    out_path = Path(__file__).resolve().parent.parent / "docs" / "biject_to_compatibility.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md)
    print(f"Wrote {out_path}", file=sys.stderr)

    bad = [r for r in rows
           if r.name in LOAD_BEARING and r.status not in ("ok", "known-issue")]
    if bad:
        print("FAIL: load-bearing distributions failed without workaround:",
              file=sys.stderr)
        for r in bad:
            print(f"  {r.name}: {r.status} ({r.detail})", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
